apiVersion: v1
kind: Pod
metadata:
 name: react-nginx
 labels:
   app: react-nginx-app
   pod-template-hash: ff6768df4
spec:
  containers:
  - name: react-nginx-app
    image: react/nginx:0.1
    ports:
    - containerPort: 80